from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = BASE_DIR / "assets"
UI_ASSETS_DIR = ASSETS_DIR / "ui"

MENU_BACKGROUND_PATH = UI_ASSETS_DIR / "menu_background.png"
BUTTON_IMAGE_PATH = UI_ASSETS_DIR / "button.png"

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "Tower Defence"
FPS = 60

SIDEBAR_WIDTH = 320
GAME_AREA_WIDTH = WINDOW_WIDTH - SIDEBAR_WIDTH
GAME_AREA_HEIGHT = WINDOW_HEIGHT

BUTTON_WIDTH = 260
BUTTON_HEIGHT = 90
BUTTON_GAP = 30

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)